language: csharp
mono: none
dotnet: 2.1.605

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

#cache:
#  directories:
#    - $TRAVIS_BUILD_DIR/snaps-cache

os:
  - linux
  - osx

install:
  - ./Tools/Travis/install.sh

script:
  - ./Tools/Travis/travis.sh

addons:
  snaps:
  - name: powershell
    confinement: classic
  homebrew:
    casks:
    - powershell