version: 'Build #{build}'
image: Visual Studio 2017
configuration: Release
environment:
  # Don't bother setting up a cache
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  
  matrix:
    - CLR: Full
    - CLR: Core
for:
-
  matrix:
    only:
      - CLR: Full
  build_script:
  - ps: Write-Host "I'm $PSEdition!"
-
  matrix:
    only:
      - CLR: Core
  build_script:
  - pwsh: Write-Host "I'm $PSEdition!"
skip_commits:
  files:
    - '**/*.md'
    - '*.yml'
