name: .NET
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    steps:
      - uses: actions/checkout@v2

      - name: Remove Existing .NET versions
        run: rm -rf ~/.dotnet

      - name: Remove Bad Versions of Pester
        run: sudo pwsh -c "Get-Module Pester -ListAvailable | Uninstall-Module -Force"

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.605

      - name: Install Dependencies
        run: pwsh -c "ipmo ./build/CI/GitHub.psm1 -DisableNameChecking; Invoke-GitHubInstall"

      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3

      - name: Build/Test
        run: |
          LANG="en_US.utf8"
          export LANG
          pwsh -c "ipmo ./build/CI/GitHub.psm1 -DisableNameChecking; Invoke-GitHubScript"